replicaCount: 1

imagex:
  repository: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0  
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080

