apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-09T18:59:15Z"
  labels:
    app: hello-minikube
  name: hello-minikube
  namespace: default
  resourceVersion: "702"
  uid: ce736329-655b-48d5-a0ca-6e45ab89ecf8
spec:
  clusterIP: 10.111.138.70
  clusterIPs:
  - 10.111.138.70
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30925
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-minikube
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
